name       : libfreehand
version    : 0.1.1
release    : 1
source     :
    - http://dev-www.libreoffice.org/src/libfreehand/libfreehand-0.1.1.tar.xz : ec6676d0c63f7feac7801a1fe18dd7abe9044b39c3882fc99b9afef39bdf1d30
license    : MPL-2.0
component  : programming
summary    : Library for parsing the FreeHand file format structure
description: |
    Library for parsing the FreeHand file format structure.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(librevenge-0.0)
    - gperf
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
